version: '3'
services:

  service-eureka:
    image: service-eureka
    restart: always


  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "rootroot" #must be change in prod
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:rw
      - mediscreenDB:/var/lib/mysql:rw

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot #must be change in prod
    restart: always
    volumes:
      - mediscreenDB:/data/db




  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  service-gateway:
    image: service-gateway
    environment:
      - JAVA_TOOL_OPTIONS=
        -DEUREKA_HOST=service-eureka
        -DZIPKIN_HOST="zipkin"
    restart: always
    ports:
      - "8888:8888"

  microservice-patient:
    image: microservice-patient
    environment:
      - JAVA_TOOL_OPTIONS=
        -DMYSQL_HOST="mysqldb"
        -DMYSQL_USER="root"
        -DMYSQL_PASSWORD="rootroot"
        -DEUREKA_HOST="service-eureka"
        -DZIPKIN_HOST="zipkin"

    depends_on:
      - mysqldb

  service-ui:
    image: service-ui
    environment:
      - JAVA_TOOL_OPTIONS=
        -DEUREKA_HOST="service-eureka"
        -DZIPKIN_HOST="zipkin"

volumes:
  mediscreenDB: