version: '3'
services:

  service-eureka:
    image: service-eureka
    restart: always


  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "rootroot" #must be change in prod
    restart: always
    volumes:
      - ./docker-entrypoint/patient.sql:/docker-entrypoint-initdb.d/patient.sql:ro
      - mysql_db:/var/lib/mysql:rw

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot #must be change in prod
    restart: always
    volumes:
      - ./docker-entrypoint/note.js:/docker-entrypoint-initdb.d/note.js:ro
      - mongo_db:/data/db
      - mongo_db:/data/configdb
    ports:
      - "27017:27017"


  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  service-gateway:
    image: service-gateway
    environment:
      - JAVA_TOOL_OPTIONS=
        -DEUREKA_HOST=service-eureka
        -DZIPKIN_HOST="zipkin"
    restart: always
    ports:
      - "8888:8888"

  microservice-patient:
    image: microservice-patient
    environment:
      - JAVA_TOOL_OPTIONS=
        -DMYSQL_HOST="mysqldb"
        -DMYSQL_USER="root"
        -DMYSQL_PASSWORD="rootroot"
        -DEUREKA_HOST="service-eureka"
        -DZIPKIN_HOST="zipkin"
    depends_on:
      - mysqldb

  microservice-note:
    image: microservice-note
    environment:
      - JAVA_TOOL_OPTIONS=
        -DMONGO_HOST="mongodb"
        -DMONGO_USER="root"
        -DMONGO_PASSWORD="rootroot"
        -DEUREKA_HOST="service-eureka"
        -DZIPKIN_HOST="zipkin"
    depends_on:
      - mongodb
    ports:
      - 8082:8082

  microservice-score:
    image: microservice-score
    environment:
      - JAVA_TOOL_OPTIONS=        
        -DEUREKA_HOST="service-eureka"
        -DZIPKIN_HOST="zipkin"

  service-ui:
    image: service-ui
    environment:
      - JAVA_TOOL_OPTIONS=
        -DEUREKA_HOST="service-eureka"
        -DZIPKIN_HOST="zipkin"

volumes:
  mysql_db:
  mongo_db: