server:
  port: 8888

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-patient
          uri: lb://microservice-patient
          predicates:
            - Path=/mediscreen/api/patient/**
          filters:
            - StripPrefix=2

        - id: microservice-note
          uri: lb://microservice-note
          predicates:
            - Path=/mediscreen/api/note/**
          filters:
            - StripPrefix=2

        - id: microservice-score
          uri: lb://microservice-score
          predicates:
            - Path=/mediscreen/api/score/**
          filters:
            - StripPrefix=2

        - id: service-ui
          uri: lb://service-ui
          predicates:
            - Path=/mediscreen/ui/**
          filters:
            - StripPrefix=2


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:9102/eureka/
  instance:
    preferIpAddress: true


management:
  #Micrometer
  tracing:
    sampling:
      probability : 1.0
  #Zipkin
  zipkin:
    tracing:
      endpoint : http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans